name: tasks-app

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-tasks_db}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-tasks_db}"]
      interval: 5s
      timeout: 3s
      retries: 20


  redis:
    image: redis:6.2
    ports:
      - ${DB_REDIS:-6379}:6379

  migrate:
    build: .
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-tasks_db}
    entrypoint: ["bun", "run", "migrate"]

  app:
    build: .
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

    environment:
      NODE_ENV: ${NODE_ENV:-production}

      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-tasks_db}

      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-""}
    ports:
      - ${API_PORT:-3000}:3000
    working_dir: /app
    command: ["bun", "run", "migrate"]

volumes:
  postgres_data:
